version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
      - "443:443"
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
    volumes:
      - .:/app
      - /etc/letsencrypt/live/spacey.dns.army/fullchain.pem:/app/fullchain.pem:ro
      - /etc/letsencrypt/live/spacey.dns.army/privkey.pem:/app/privkey.pem:ro